### ISSUE TITLE
Auto highlight + dynamic imports in vite?

### ISSUE THREAD

**Issue by Blakeinstein** [rexxars/react-lowlight#15]
I was interested in if the package supports `lowlight.highlightAuto` to figure out language and highlight automatically? And additionally import the language as well?

**Comment by sibiraj-s** [comment]
If you don't pass the language option to `Lowlight` component it falls back to `highlightAuto`. The language is not imported automatically if not found. You'll need to implement that yourself. See [Dynamic Loading](https://github.com/rexxars/react-lowlight#dynamic-loading) for more info.

**Comment by sibiraj-s** [comment]
Closing this issue as answered. Feel free to continue the discussion if required.
