### ISSUE TITLE
How to use in a markdown?

### ISSUE THREAD

**Issue by billcastillo** [rexxars/react-lowlight#4]
```
const content = `
\`\`\css
.wrapper {
  display: block;
}
\`\`\`
`

<Markdown source={content} escapeHtml={false} />
```

You tried posting an example [here](https://github.com/rexxars/react-markdown/issues/58) but is now 404

**Comment by sibiraj-s** [comment]
Closing this, since its too old and I guess the solution would have been figured out by this time.
