### ISSUE TITLE
Update to lowlight 2 and fix vulnerabilities

### ISSUE THREAD

**Issue by ghost** [rexxars/react-lowlight#8]
- Update to lowlight v2. 
- Update to highlight.js v11 (current dependent version has some vulnerabilities)

**Comment by ghost** [comment]
@rexxars. I can work on this. I can dump everything to latest and raise a maintenance PR. It can be released as new major (v3)

**Comment by rexxars** [comment]
Sounds great! 
I assume we'd have to/should make this module ESM only to align with lowlight as well? Thoughts?

**Comment by sibiraj-s** [comment]
Yeah. That would be great too. We can use also rollup to provide an cjs/umd(browser) build to other environments as well.  

These top of my head thoughts.

- move to modules
- updates all dependencies
- webpack -> rollup
- vite instead of webpack for demo server/build
- travis to Github Actions

**Comment by rexxars** [comment]
All good changes :)
